"""
Generate dbt staging SQL for WIDE-format hospital price transparency tables,
using BigQuery's native UNPIVOT operator.

Wide files (NYU Langone, Albany, Brooklyn, Flushing) encode every payer-plan as
its OWN set of 4 columns:
    standard_charge_{payer_plan}_negotiated_dollar
    standard_charge_{payer_plan}_negotiated_percentage
    standard_charge_{payer_plan}_negotiated_algorithm
    standard_charge_{payer_plan}_methodology

To reach the common long target shape (one row per procedure per payer-plan),
we UNPIVOT these column-groups into rows. An earlier version emitted one
SELECT ... UNION ALL per payer-plan; that works for small files but a 413-plan
file (NYU Langone) produced ~286K chars of SQL and blew BigQuery's view-length
AND query-parse-memory limits. BigQuery's native multi-column UNPIVOT lists
each column once instead of repeating whole SELECT blocks, so it stays compact
even for hundreds of payer-plans.

Multi-column UNPIVOT groups the 4 metrics as a tuple and lists one tuple per
payer-plan in the IN clause, aliasing each to its payer-plan label:

    UNPIVOT (
      (negotiated_dollar, negotiated_percentage, negotiated_algorithm, methodology)
      FOR payer_plan IN (
        (col_a_dollar, col_a_pct, col_a_algo, col_a_method) AS 'PAYER_PLAN_A',
        ...
      )
    )

Requirement: every payer-plan must have all 4 metric columns AND matching types.
Since we loaded everything as STRING, all columns share type -- so we UNPIVOT as
strings, then SAFE_CAST the numeric ones afterward. Payer-plan boundary is not
separable post-sanitization (Finding 8), so payer_plan keeps the full label.

Usage:
    python generate_wide_unpivot_sql.py <raw_table> <ccn> "<hospital_name>" <out_model_name>
"""

import os
import sys
from collections import defaultdict
from google.cloud import bigquery

PROJECT = os.environ["GCP_PROJECT_ID"]
SUFFIXES = ["negotiated_dollar", "negotiated_percentage",
            "negotiated_algorithm", "methodology"]
ID_COLS = ["code_1", "code_1_type", "description",
           "standard_charge_gross", "standard_charge_discounted_cash", "setting"]


def get_columns(raw_table):
    client = bigquery.Client(project=PROJECT)
    t = client.get_table(f"{PROJECT}.raw.{raw_table}")
    return [f.name for f in t.schema]


def group_by_payer_plan(cols):
    groups = defaultdict(dict)
    for c in cols:
        for suf in SUFFIXES:
            marker = f"_{suf}"
            if c.startswith("standard_charge_") and c.endswith(marker):
                stem = c[len("standard_charge_"):-len(marker)]
                if stem:
                    groups[stem][suf] = c
                break
    # keep only payer-plans that have ALL 4 metric columns (UNPIVOT needs them aligned)
    complete = {stem: m for stem, m in groups.items()
                if all(suf in m for suf in SUFFIXES)}
    dropped = len(groups) - len(complete)
    return complete, dropped


def sql_str_literal(s):
    return "'" + s.replace("'", "''") + "'"


def main():
    if len(sys.argv) != 5:
        print(__doc__)
        sys.exit(1)
    raw_table, ccn, hospital_name, model_name = sys.argv[1:5]

    cols = get_columns(raw_table)
    id_cols_present = [c for c in ID_COLS if c in cols]
    groups, dropped = group_by_payer_plan(cols)

    if not groups:
        print(f"ERROR: no complete payer-plan column groups found in {raw_table}.")
        sys.exit(1)

    # Build the IN clause: one 4-tuple per payer-plan, aliased to its label.
    in_items = []
    for stem, m in sorted(groups.items()):
        tup = ", ".join(m[suf] for suf in SUFFIXES)
        in_items.append(f"      ({tup}) as {sql_str_literal(stem)}")
    in_clause = ",\n".join(in_items)

    id_select = ",\n        ".join(id_cols_present)

    # NYU-scale files: materialize as table (views cap at 256K chars; a big
    # UNPIVOT is fine as a table and avoids re-running on every read).
    config = "{{ config(materialized='table') }}\n\n" if len(groups) > 150 else ""

    sql = f"""{config}-- Staging model: price transparency -- {hospital_name} (WIDE format, UNPIVOT)
--
-- AUTO-GENERATED by generate_wide_unpivot_sql.py from raw.{raw_table}.
-- {len(groups)} payer-plans unpivoted via native BigQuery multi-column UNPIVOT.
-- {dropped} payer-plan(s) dropped for missing one of the 4 metric columns.
-- Do not hand-edit; regenerate if the source schema changes.
--
-- All raw columns are STRING, so we UNPIVOT as strings then SAFE_CAST numerics.
-- payer_plan keeps the full sanitized label (payer|plan boundary lost at load,
-- Finding 8). code_1 -> code, code_1_type -> code_type applied in final wrapper.

with source as (

    select * from {{{{ source('raw', '{raw_table}') }}}}

),

unpivoted as (

    select
        {id_select},
        payer_plan,
        negotiated_dollar,
        negotiated_percentage,
        negotiated_algorithm,
        methodology
    from source
    unpivot (
      (negotiated_dollar, negotiated_percentage, negotiated_algorithm, methodology)
      for payer_plan in (
{in_clause}
      )
    )

),

final as (

    select
        '{ccn}' as ccn,
        {sql_str_literal(hospital_name)} as hospital_name,
        code_1 as code,
        code_1_type as code_type,
        description,
        setting,
        payer_plan,
        cast(null as string) as payer_name,   -- payer/plan not separable post-sanitization
        payer_plan as plan_name,
        safe_cast(standard_charge_gross as float64) as gross_charge,
        safe_cast(standard_charge_discounted_cash as float64) as discounted_cash_charge,
        safe_cast(negotiated_dollar as float64) as negotiated_dollar,
        safe_cast(negotiated_percentage as float64) as negotiated_percentage,
        negotiated_algorithm,
        methodology
    from unpivoted

)

select * from final
where negotiated_dollar is not null
   or negotiated_percentage is not null
   or negotiated_algorithm is not null
"""

    out_path = f"{model_name}.sql"
    with open(out_path, "w") as f:
        f.write(sql)
    print(f"Wrote {out_path}: {len(groups)} payer-plans via UNPIVOT "
          f"({dropped} dropped for incomplete metric set), "
          f"{'materialized as table' if config else 'materialized as view'}.")


if __name__ == "__main__":
    main()
